In [1]:
[[123, 12, 123, 12, 33], [], []]

[[123, 12, 123, 12, 33], [], []]

In [9]:
import numpy
n = numpy.arange(27)

In [3]:
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [7]:
n1 = n.reshape(3, 3, 3)
print(n1)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [23]:
m = numpy.asarray([[123, 12, 123, 12, 33], [], []])
type(m)

C:\Users\Acer\AppData\Local\Temp/ipykernel_11820/2413937912.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  m = numpy.asarray([[123, 12, 123, 12, 33], [], []])


numpy.ndarray

In [12]:
print(m)

[list([123, 12, 123, 12, 33]) list([]) list([])]


In [13]:
import sys
!{sys.executable} -m pip install opencv-python

In [14]:
import cv2

In [20]:
im_g = cv2.imread("smallgray.png", 0)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [21]:
im_g2 = cv2.imwrite("smallgray2.png", im_g)

In [22]:
im_g2

True

In [24]:
im_g[2, 0]

209

In [25]:
for i in im_g:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [26]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [30]:
imhs = numpy.hstack((im_g, im_g))
print (imhs)

[[187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182]]


In [31]:
imvs = numpy.vstack((im_g, im_g))
print (imvs)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [33]:
imhsl = numpy.hsplit(imhs, 2)
print (imhsl)

[array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8), array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)]


In [36]:
imvsl = numpy.vsplit(imvs, 2)
print (imvsl)

[array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8), array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)]
